### ISSUE TITLE
It is slow to read data with json

### ISSUE THREAD

**Issue by sofsoo1995** [fabbrimatteo/JTA-Dataset#1]
Hi !
First, thank you for your useful work !

In your wiki, you suggest to use json to load the file like this:
  ```
  import json
   import numpy as np

   json_file_path = 'annotations/training/seq_42.json'

    with open(json_file_path, 'r') as json_file:
        matrix = json.load(json_file)
        matrix = np.array(matrix)
```

However, I find it very slow... ~7s to load one matrix. I've saved np.save and loaded with np.load. it has taken ~0.3s. So, in my opinion, it is better to store the annotation file using npy.

I think that it would be great if we could use COCO api to load the annotations(like Posetrack).
Also, I want to use JTA and Posetrack jointly but the joint types are not the same(nose and head bottom are missing)

**Comment by fabbrimatteo** [comment]
#### JSON vs NPY
Thanks for the suggestion, but we have chosen the json format for portability reasons. 
The idea of storing the annotations using numpy is indeed the best solution to speed up the reads. We will write a note about this in the README.

#### COCO-Style Annotations
COCO style annotations are coming soon!

#### Missing Joints
Actually, the head bottom joint is present in the annotations: we have named it neck. 
The nose, instead, is not present because the game API that extracts body joint locations does not handle the nose.

**Comment by fabbrimatteo** [comment]
Hi @sofsoo1995,
We have added the support to COCO-Style annotations.
Let me know if something is missing.

**Comment by sofsoo1995** [comment]
thank you for this adding ! Occlusions and tracking information are missing(as precised). Unfortunatly, these annotations are rather important for me but I think I can handle this.
